// Service and mock data for quiz results

export function getMockQuizResults() {
    return {
        mode: 'exam',
        score: 85,
        totalQuestions: 10,
        timeSpent: 420,
        answers: [
            {
                questionId: 'q1',
                question: 'What is the capital of France?',
                userAnswer: 'Paris',
                correctAnswer: 'Paris',
                isCorrect: true,
                timeSpent: 30,
                attempts: 1,
            },
            {
                questionId: 'q2',
                question: 'What is 2 + 2?',
                userAnswer: '4',
                correctAnswer: '4',
                isCorrect: true,
                timeSpent: 20,
                attempts: 1,
            },
            {
                questionId: 'q3',
                question: 'What is the boiling point of water?',
                userAnswer: '100',
                correctAnswer: '100',
                isCorrect: true,
                timeSpent: 40,
                attempts: 1,
            },
            {
                questionId: 'q4',
                question: 'Who wrote Hamlet?',
                userAnswer: 'Shakespeare',
                correctAnswer: 'Shakespeare',
                isCorrect: true,
                timeSpent: 50,
                attempts: 1,
            },
            {
                questionId: 'q5',
                question: 'What is the largest planet?',
                userAnswer: 'Jupiter',
                correctAnswer: 'Jupiter',
                isCorrect: true,
                timeSpent: 60,
                attempts: 1,
            },
            {
                questionId: 'q6',
                question: 'What is the chemical symbol for gold?',
                userAnswer: 'Au',
                correctAnswer: 'Au',
                isCorrect: true,
                timeSpent: 30,
                attempts: 1,
            },
            {
                questionId: 'q7',
                question: 'What is the square root of 16?',
                userAnswer: '4',
                correctAnswer: '4',
                isCorrect: true,
                timeSpent: 25,
                attempts: 1,
            },
            {
                questionId: 'q8',
                question: 'What is the speed of light?',
                userAnswer: '299,792,458 m/s',
                correctAnswer: '299,792,458 m/s',
                isCorrect: true,
                timeSpent: 45,
                attempts: 1,
            },
            {
                questionId: 'q9',
                question: 'What is the currency of Japan?',
                userAnswer: 'Yen',
                correctAnswer: 'Yen',
                isCorrect: true,
                timeSpent: 60,
                attempts: 1,
            },
            {
                questionId: 'q10',
                question: 'What is the smallest prime number?',
                userAnswer: '1',
                correctAnswer: '2',
                isCorrect: false,
                timeSpent: 60,
                attempts: 2,
            },
        ],
    };
}
