services:
  database:
    container_name: education-system-database
    image: postgres:latest
    ports:
      - 5433:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: education-system-cloudbeaver
    restart: always
    ports:
      - 8978:8978
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - network

  backend:
    container_name: education-system-backend
    environment:
      # Database Configuration
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: ${PG_USER}
      DATABASE_PASSWORD: ${PG_PASS}
      DATABASE_NAME: ${PG_DB}
      DATABASE_SSLMODE: disable

      # Server Configuration
      SERVER_PORT: ${SERVER_PORT}
      SERVER_MODE: ${SERVER_MODE}

      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      # AWS/S3 Configuration
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
    image: ${REGISTRY}/backend:latest
    restart: always
    networks:
      - network
    depends_on:
      - database
      - redis
    profiles:
      - backend
      - deploy

  redis:
    container_name: education-system-redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - network

  frontend:
    container_name: education-system-frontend
    image: ${REGISTRY}/frontend:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
    profiles:
      - frontend
      - deploy

networks:
  network:
    name: education-system-network
    external: true

volumes:
  database:
    name: education-system-database
    external: true
  cloudbeaver:
    name: education-system-cloudbeaver
    driver: local
