export const mockQuizData = {
    title: 'Mathematics Quiz - Algebra',
    totalQuestions: 20,
    timeLimit: 30, // minutes
    questions: [
        {
            id: 1,
            question: 'What is the solution to the equation 2x + 5 = 13?',
            type: 'multiple_choice',
            options: {
                A: 'x = 4',
                B: 'x = 6',
                C: 'x = 8',
                D: 'x = 9',
            },
            correctAnswer: 'A',
        },
        {
            id: 2,
            question: 'Simplify the expression: (x + 2)(x - 3)',
            type: 'multiple_choice',
            options: {
                A: 'x² - x - 6',
                B: 'x² + x - 6',
                C: 'x² - x + 6',
                D: 'x² + x + 6',
            },
            correctAnswer: 'A',
        },
        {
            id: 3,
            question: 'Solve for x: 3x - 7 = 14',
            type: 'multiple_choice',
            options: {
                A: 'x = 5',
                B: 'x = 7',
                C: 'x = 9',
                D: 'x = 11',
            },
            correctAnswer: 'B',
        },
        {
            id: 4,
            question: 'What is the value of x in the equation 5x + 3 = 28?',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = 5',
                C: 'x = 7',
                D: 'x = 9',
            },
            correctAnswer: 'B',
        },
        {
            id: 5,
            question: 'Factor the expression: x² - 9',
            type: 'multiple_choice',
            options: {
                A: '(x + 3)(x - 3)',
                B: '(x + 9)(x - 1)',
                C: '(x + 3)(x + 3)',
                D: '(x - 3)(x - 3)',
            },
            correctAnswer: 'A',
        },
        {
            id: 6,
            question: 'Solve: 2x + 4 = 10',
            type: 'multiple_choice',
            options: {
                A: 'x = 2',
                B: 'x = 3',
                C: 'x = 4',
                D: 'x = 5',
            },
            correctAnswer: 'B',
        },
        {
            id: 7,
            question: 'What is the solution to x² = 16?',
            type: 'multiple_choice',
            options: {
                A: 'x = 4',
                B: 'x = -4',
                C: 'x = ±4',
                D: 'x = 8',
            },
            correctAnswer: 'C',
        },
        {
            id: 8,
            question: 'Simplify: (x + 1)²',
            type: 'multiple_choice',
            options: {
                A: 'x² + 1',
                B: 'x² + 2x + 1',
                C: 'x² + x + 1',
                D: 'x² + 2',
            },
            correctAnswer: 'B',
        },
        {
            id: 9,
            question: 'Solve: 4x - 8 = 12',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = 4',
                C: 'x = 5',
                D: 'x = 6',
            },
            correctAnswer: 'C',
        },
        {
            id: 10,
            question: 'What is the value of x in 3x + 6 = 21?',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = 5',
                C: 'x = 7',
                D: 'x = 9',
            },
            correctAnswer: 'B',
        },
        {
            id: 11,
            question: 'Factor: x² - 4x + 4',
            type: 'multiple_choice',
            options: {
                A: '(x - 2)²',
                B: '(x + 2)²',
                C: '(x - 2)(x + 2)',
                D: '(x - 4)(x + 1)',
            },
            correctAnswer: 'A',
        },
        {
            id: 12,
            question: 'Solve: 5x + 10 = 35',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = 5',
                C: 'x = 7',
                D: 'x = 9',
            },
            correctAnswer: 'B',
        },
        {
            id: 13,
            question: 'What is the solution to 2x² = 18?',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = -3',
                C: 'x = ±3',
                D: 'x = 9',
            },
            correctAnswer: 'C',
        },
        {
            id: 14,
            question: 'Simplify: (x - 3)(x + 3)',
            type: 'multiple_choice',
            options: {
                A: 'x² - 9',
                B: 'x² + 9',
                C: 'x² - 6x + 9',
                D: 'x² + 6x + 9',
            },
            correctAnswer: 'A',
        },
        {
            id: 15,
            question: 'Solve: 6x - 12 = 24',
            type: 'multiple_choice',
            options: {
                A: 'x = 4',
                B: 'x = 6',
                C: 'x = 8',
                D: 'x = 10',
            },
            correctAnswer: 'B',
        },
        {
            id: 16,
            question: 'What is the value of x in 7x + 14 = 49?',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = 5',
                C: 'x = 7',
                D: 'x = 9',
            },
            correctAnswer: 'B',
        },
        {
            id: 17,
            question: 'Factor: x² + 6x + 9',
            type: 'multiple_choice',
            options: {
                A: '(x + 3)²',
                B: '(x - 3)²',
                C: '(x + 3)(x - 3)',
                D: '(x + 9)(x - 1)',
            },
            correctAnswer: 'A',
        },
        {
            id: 18,
            question: 'Solve: 8x - 16 = 32',
            type: 'multiple_choice',
            options: {
                A: 'x = 4',
                B: 'x = 6',
                C: 'x = 8',
                D: 'x = 10',
            },
            correctAnswer: 'B',
        },
        {
            id: 19,
            question: 'What is the solution to 3x² = 27?',
            type: 'multiple_choice',
            options: {
                A: 'x = 3',
                B: 'x = -3',
                C: 'x = ±3',
                D: 'x = 9',
            },
            correctAnswer: 'C',
        },
        {
            id: 20,
            question: 'Simplify: (x + 4)(x - 4)',
            type: 'multiple_choice',
            options: {
                A: 'x² - 16',
                B: 'x² + 16',
                C: 'x² - 8x + 16',
                D: 'x² + 8x + 16',
            },
            correctAnswer: 'A',
        },
    ],
};
