on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          docker compose -f compose.build.yaml --profile frontend build
          docker compose -f compose.build.yaml --profile frontend push

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        run: |
          docker compose -f compose.build.yaml --profile backend build
          docker compose -f compose.build.yaml --profile backend push

  deploy:
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASS }}
      PG_DB: ${{ secrets.PG_DB }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy down --rmi all -v
      - name: Deploy Application
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy up -d
