on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASS }}
      PG_DB: ${{ secrets.PG_DB }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy down --rmi all -v
      - name: Deploy Application
        run: docker compose -f compose.yaml -p blood-donation-system --profile deploy up -d
